Functional: Handling a button click and data transfer.
Kvantorium16/schedule pull request #13
Opened 2021-06-02 20:02 UTC by Desempell

Попытался реализовать передачу данных, вроде сделал верно, но возникла ошибка. 
_Не нашел ее решения, можете помощь с этим?_

2021-06-08 14:19 UTC, Kvantorium16 requested changes

2021-06-08 14:19 UTC, Kvantorium16 commented on app/src/main/java/com/example/schedule/SecondActivity.kt
> +
Здесь можно использовать такой синтаксис:
```
when (message) {
   "IT-квантум" -> {
      direction.text = "IT-квантум"
      description.text = "Углубленное изучение программирования, сетевых технологий."
   }
   "Геоквантум" -> {
      direction.text = "Геоквантум"
      description.text = "Работа с дистанционным зондированием Земли."
   }
   else -> {
      
   }
}
```

2021-06-08 14:19 UTC, Kvantorium16 commented on app/src/main/java/com/example/schedule/MainActivity.kt
> +    var objViewPager: ViewPager? = findViewById(R.id.viewPager);
Ты не можешь здесь так сделать, так как эта строчка вызовется до onCreate() (или любой другой функции класса), а к этому времени лейаут ещё не привязан к этому активити. Короче, вызывай findViewById(R.id.viewPager) уже внутри onCreate(), а лучше вообще в onResume().

2021-06-08 14:25 UTC, Kvantorium16 commented
Ещё нужно добавить вот такую строчку в `AndroidManifest.xml: <activity android:name=".SecondActivity"></activity>`.

2021-06-08 14:46 UTC, Desempell commented
Исправил всё, что вы отметили. Объявление objViewPager переместил в OnCreate.

2021-06-12 10:22 UTC, Kvantorium16 commented
А зачем `@SuppressLint("SetTextI18n")`?

2021-06-12 10:22 UTC, merged