Fix parser
Kvantorium16/schedule pull request #20
Opened 2021-06-20 11:44 UTC by Jpegga

Исправил все возможные бесконечные циклы. 
Оптимизировал код убрав doc.select в циклах

2021-06-20 15:32 UTC, Kvantorium16 requested changes
Большая часть проблем тобой решена, остались мелочи.

2021-06-20 15:32 UTC, Kvantorium16 commented on app/src/main/java/com/example/schedule/HtmlParser.kt
>                  val doc: Document = Jsoup.connect("https://jjpega.pythonanywhere.com/get").get()
Я думаю, нужно перенести функции `db.clear_directions_table()` и `db.clear_lessons_table()` внутрь `try {}`, после `val doc: Document = Jsoup.connect("https://jjpega.pythonanywhere.com/get").get()`. Так, таблицы не будут очищены, если не удалось подключится к сайту.

2021-06-20 15:32 UTC, Kvantorium16 commented on app/src/main/java/com/example/schedule/HtmlParser.kt
> +                        groups = group.split(" ") as ArrayList<String>
`groups `тоже нужно реализовать через _Elements_. (смотри ревью к предыдущему ПР).

2021-06-20 15:32 UTC, Kvantorium16 commented on app/src/main/java/com/example/schedule/HtmlParser.kt
>                          val day: Elements = doc.select(str)
```suggestion
                        val day: Elements = doc.select("table[id='" + days + "_" + direction + "']")
```

2021-06-21 07:06 UTC, Jpegga commented
Отправил исправления проверьте

2021-06-21 07:15 UTC, merged

2021-06-21 07:31 UTC, Kvantorium16 approved these changes
Класс!
Пару ошибок я ещё исправил, вот они:

2021-06-21 07:31 UTC, Kvantorium16 commented on app/src/main/java/com/example/schedule/HtmlParser.kt
> +                            db.group_add(group.toString(), directions[i])
Здесь должно быть `group.text()`, не `group.toString()`, иначе html-теги опять попадают в таблицу.

2021-06-21 07:31 UTC, Kvantorium16 commented on app/src/main/java/com/example/schedule/HtmlParser.kt
> +                    groups = tr!![i].select("p[id=\"group\"]")
Где-то здесь пришлось убирать из массива повторяющиеся группы.

2021-06-21 08:02 UTC, Kvantorium16 commented
Нужно срочно сделать одну вещь: заполнить расписание на сайте информацией, чтобы во время защиты она отображалась в приложении.
![image](https://user-images.githubusercontent.com/81939891/122727868-2f87ae00-d280-11eb-8f9b-fd7668fc8849.png)

2021-06-21 08:03 UTC, Kvantorium16 commented
И смени название "Промышленная робототехника" на "Робоквантум" на сайте, пожалуйста.